// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Access: typeof import('./components/errors/Access.vue')['default']
    AccountSettings: typeof import('./components/profile/AccountSettings.vue')['default']
    AppConfig: typeof import('./components/layout/AppConfig.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppMenu: typeof import('./components/layout/AppMenu.vue')['default']
    AppSubmenu: typeof import('./components/layout/AppSubmenu.vue')['default']
    AppTopBar: typeof import('./components/layout/AppTopBar.vue')['default']
    CardWrapper: typeof import('./components/shared/CardWrapper.vue')['default']
    CompanyForm: typeof import('./components/forms/CompanyForm.vue')['default']
    EmptyPage: typeof import('./components/shared/EmptyPage.vue')['default']
    Error: typeof import('./components/errors/Error.vue')['default']
    FormContentCreator: typeof import('./components/shared/FormContentCreator.vue')['default']
    NotFound: typeof import('./components/errors/NotFound.vue')['default']
    PreferencesSettings: typeof import('./components/profile/PreferencesSettings.vue')['default']
    ProductForm: typeof import('./components/forms/ProductForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableView: typeof import('./components/shared/TableView.vue')['default']
  }
}

export {}
