apiVersion: apps/v1
kind: Deployment
metadata:
  name: "arq-zipcode-deploy"
spec:
  selector:
    matchLabels:
      app: "arq-zipcode"
  replicas: 2
  template:
    metadata:
      labels:
        app: "arq-zipcode"
    spec:
      containers:
      - image: "757992231822.dkr.ecr.eu-west-1.amazonaws.com/arq-zipcode-ws:TAG"
        name: "arq-zipcode"
        env:
          - name: ENV
            value: "ENVR"
          - name: APP_VERSION
            value: "TAG"
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: arq-zipcode-secret
                key: pg_pass
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 0.1
