[tool.poetry]
name = "qsdl"
version = "3.1.0"
description = "A Schema-Definition-Language Generator inspired by GraphQl."
authors = ["henn1001 <henn1001@outlook.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://gitlab.com/henn1001/qsdl"
repository = "https://gitlab.com/henn1001/qsdl"
include = [
    "README.md",
]

[tool.poetry.dependencies]
python = "^3.7"
textX = "2.3.0"
Jinja2 = "3.0.3"
PyYAML = "6.0"
plantuml = "0.3.0"
click = "8.0.4"
pathspec = "0.9.0"
stringcase = "1.2.0"
pyfiglet = "0.8.post1"
dacite = "1.6.0"
inquirer = "2.9.1"
Random-Word = "1.0.7"

[tool.poetry.dev-dependencies]
pylint = "2.12.2"
black = "22.1.0"
pytest = "7.0.1"
pytest-cov = "3.0.0"
graphql-core = "3.2.0"
openapi-spec-validator = "0.4.0"

[tool.poetry.scripts]
qsdl = "qsdl.__main__:entrypoint"

[tool.pytest.ini_options]
junit_family = "xunit2"
addopts = "--junitxml=dist/tests/report.xml --cov=qsdl --cov-report term --cov-report html:dist/coverage"
testpaths = [
    "tests",
]

[tool.pylint.SIMILARITIES]
min-similarity-lines = 10

[tool.pylint.messages_control]
disable = [
    "protected-access",
    "bad-continuation",
    "too-few-public-methods",
    "too-many-instance-attributes",
    "line-too-long",
    "duplicate-code",
    "cyclic-import",
]

[tool.black]
line-length = 120

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING:",
]

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"
