apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
    name: eks-tendam-prod
    region: eu-west-1
nodeGroups:
    - name: eks-ng-tendam-spot-prod
      minSize: 0
      maxSize: 2
      desiredCapacity: 1
      privateNetworking: true
      instancesDistribution:
        instanceTypes: ["t3.medium"]
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        spotAllocationStrategy: lowest-price
      ssh:
        allow: true
        publicKeyName: 'eks-keypair-tendam-prod'
      labels:
        role: worker
        type: spot
        env: prod
      tags:
        k8s.io/cluster-autoscaler/node-template/label/role: worker
        k8s.io/cluster-autoscaler/node-template/label/type: spot
        k8s.io/cluster-autoscaler/node-template/label/env: prod
      iam:
        withAddonPolicies:
          autoScaler: true
          cloudWatch: true
          albIngress: true
