version: '3'

volumes:
  postgres_data:
    driver: local

networks:
  proxynet:
    name: maas_network

services:

  # postgres:
  #   image: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./utils/postgres:/docker-entrypoint-initdb.d
  #   environment:
  #     POSTGRES_MULTIPLE_DATABASES: serviceportal,keycloak
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - 5433:5432
  #   networks:
  #     proxynet:
  #       aliases:
  #         - sp-postgres

  # keycloak:
  #   image: quay.io/keycloak/keycloak:legacy
  #   volumes:
  #     - ./utils/keycloak/:/config/
  #   environment:
  #     DB_VENDOR: POSTGRES
  #     DB_ADDR: sp-postgres
  #     DB_DATABASE: keycloak
  #     DB_SCHEMA: public
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     KEYCLOAK_USER: admin
  #     KEYCLOAK_PASSWORD: admin
  #     # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
  #     #JDBC_PARAMS: "ssl=true"
  #     KEYCLOAK_IMPORT: /config/keycloak-realm.json
  #   ports:
  #     - 8071:8080
  #   networks:
  #     proxynet:
  #       aliases:
  #         - sp-keycloak
  #   depends_on:
  #     - postgres

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
      target: final
    image: ${BACKEND_DOCKER_IMAGE_NAME}
    command: 
      - "--spring.datasource.url=jdbc:postgresql://mp-postgres:5432/marketplace"
      - "--spring.datasource.username=postgres"
      - "--spring.datasource.password=postgres"
      - "--spring.jpa.hibernate.ddl-auto=none"
      - "--spring.flyway.enabled=false"
      - "--spring.h2.console.enabled=false"
      - "--logging.config="
    ports:
      - 8081:8080
    networks:
      proxynet:
        aliases:
          - sp-backend
    # depends_on:
    #   - keycloak

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # use marketplace keycloak as two instances cause issues when running everything on localhost
        #- VITE_KEYCLOAK_URL=http://localhost:8071/auth
        - VITE_KEYCLOAK_URL=http://localhost:8070/auth
        - VITE_KEYCLOAK_REALM=maas
        - VITE_KEYCLOAK_CLIENTID=maas-client
    image: ${FRONTEND_DOCKER_IMAGE_NAME}
    volumes:
      - ./utils/nginx/nginx.conf:/etc/nginx/templates/default.conf.template
    environment:
      NGINX_PORT: 80
      NGINX_HOST: localhost
      # BACKEND_URL: http://service-portal.dev.maas.alpha.area2invest.li/api/v1
      BACKEND_URL: http://sp-backend:8080/api/v1
    ports:
      - 8001:80
    networks:
      proxynet:
        aliases:
          - sp-frontend
    depends_on:
      - backend